# Generated by Django 4.0.4 on 2022-05-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('done_when', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('CR', 'created'), ('ST', 'started'), ('DE', 'deleted'), ('CO', 'completed'), ('SO', 'someday')], default='CR', max_length=2)),
            ],
        ),
    ]
