version: "3.8"

services:
  backend:
    build: ./backend
    container_name: "backend"
    command: python manage.py run -h 0.0.0.0
    ports:
      - "5050:5000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - yrap_db
    networks:
      #     - nginx_network
      - db_network
    volumes:
      - ./backend/:/usr/src/app/
  # frontend:
  #   container_name: "frontend"
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  yrap_db:
    container_name: "yrap_db"
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - db_network
  # nginx:
  #   container_name: "yrap_nginx"
  #   build: ./yrap_nginx
  #   ports:
  #     - "80:80"
  #   environment:
  #     ALLOWED_HOSTS: 127.0.0.1,0.0.0.0,localhost
  # networks:
  #   - nginx_network
  # depends_on:
  #   - backend
  #   - frontend
networks:
  #   nginx_network:
  #     driver: bridge
  db_network:
    driver: bridge

volumes:
  postgres_data:
#   static_volume:
