version: '3.8'

services:
  backend:
    container_name: 'backend'
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - yrap_db
  yrap_db:
    image: postgres:14-alpine
    container_name: 'yrap_db'
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
